{{- if or .Values.aws_iam_role_arn .Values.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.aws_iam_role_arn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.aws_iam_role_arn }}
  {{- end }}
  labels:
    app: {{ include "cronjob.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ include "cronjob.name" . }}
  name: {{ default (include "cronjob.name" .) .Values.serviceAccountName }}
{{- end }}
