{{- if .Capabilities.APIVersions.Has "datadoghq.com/v1alpha1/DatadogMonitor" }}
{{- range $name, $monitor := .Values.monitors }}
{{- if $monitor.enabled }}
---
apiVersion: datadoghq.com/v1alpha1
kind: DatadogMonitor
metadata:
  name: {{ include "datadog-resources.fullname" $ }}-{{ $name }}
  namespace: {{ include "datadog-resources.namespace" $ }}
  labels:
    {{- include "datadog-resources.labels" $ | nindent 4 }}
    datadog.resource.type: monitor
    datadog.monitor.name: {{ $name }}
    {{- with $monitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $monitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $monitor.query }}
  query: {{ . | quote }}
  {{- end }}
  {{- with $monitor.type }}
  type: {{ . | quote }}
  {{- end }}
  {{- with $monitor.name }}
  name: {{ . | quote }}
  {{- end }}
  {{- with $monitor.message }}
  message: {{ . | quote }}
  {{- end }}
  {{- with $monitor.tags }}
  tags:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $monitor.priority }}
  priority: {{ . }}
  {{- end }}
  {{- with $monitor.options }}
  options:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
