# Allows you to define custom resources via a helm chart
# helm install -f values.yaml my-release .
# This will get around terraform catch 22 with crds not availble
# until after terraform apply
#
apiVersion: foo.io/v1beta1
kind: foobarbaz
metadata:
  name: foo
spec:
  baz:
    bar: foo
