apiVersion: v2
name: app
description: |
  A generic, flexible Helm chart for deploying applications on Kubernetes.
  This chart follows best practices and provides comprehensive configuration
  options for most application deployment scenarios.
type: application
version: 0.1.0

keywords:
  - application
  - kubernetes
  - generic

home: https://github.com/dnd-it/helm-charts
sources:
  - https://github.com/dnd-it/helm-charts

maintainers:
  - name: DAI
    email: abc@abc.com

annotations:
  category: Application
