# Default values for generic-app chart
# This is a YAML-formatted file.

# Global settings
global:
  labels: {}
  annotations: {}

# Application settings
app:
  # Defaults to chart name if not specified
  name: ""
  # Defaults to chart appVersion if not specified
  version: ""

# Image configuration
image:
  repository: traefik/whoami
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

# Deployment configuration
deployment:
  enabled: true
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%

  # Pod configuration
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}

  # Container configuration
  securityContext: {}
  command: []
  args: []

  # Environment variables
  env: []
  envFrom: []

  # Resource limits and requests
  resources: {}

  # Node selection
  nodeSelector: {}
  tolerations: []
  affinity: {}

  # Probes
  livenessProbe:
    enabled: false
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

  readinessProbe:
    enabled: false
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

  startupProbe:
    enabled: false
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 30
    successThreshold: 1

# Service configuration
service:
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: 80
  ports: []
  annotations: {}
  labels: {}

# Ingress configuration
ingress:
  enabled: false
  # className: ""
  # annotations: {}
  # hosts:
  #   - host: chart-example.local
  #     paths:
  #       - path: /
  #         pathType: ImplementationSpecific
  # tls: []

# ServiceAccount configuration
serviceAccount:
  enabled: true
  create: true
  name: ""
  annotations: {}
  labels: {}

# RBAC configuration
rbac:
  enabled: false
  rules: []

# ConfigMap configuration
configMap:
  enabled: false
  data: {}
  annotations: {}
  labels: {}

# Secret configuration
secret:
  enabled: false
  type: Opaque
  data: {}
  stringData: {}
  annotations: {}
  labels: {}

# PersistentVolumeClaim configuration
persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 8Gi
  storageClass: ""
  annotations: {}
  labels: {}
  mountPath: /data
  subPath: ""

# Horizontal Pod Autoscaler
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Pod Disruption Budget
podDisruptionBudget:
  enabled: false
  minAvailable: 1
  # maxUnavailable: 1

# Network Policy
networkPolicy:
  enabled: false
  policyTypes: []
  ingress: []
  egress: []

# Service Monitor (Prometheus)
serviceMonitor:
  enabled: false
  interval: 30s
  path: /metrics
  port: http
  labels: {}
  annotations: {}

# Additional volumes
volumes: []

# Additional volume mounts
volumeMounts: []

# Init containers
initContainers: []

# Sidecar containers
sidecars: []

# Pod disruption budget
pdb:
  enabled: false
  minAvailable: 1

# Extra objects to deploy
extraObjects: []
