nameOverride: complete
image_repo: public.ecr.aws/eks-distro/kubernetes/pause
image_tag: "3.9"
metadata:
  labels:
    datadog:
      env: staging-20min
      service: complete
      version: abcd123456
  deploymentAnnotations:
    downscaler/downscale-period: Mon-Sun 23:00-23:01 Europe/Zurich
    downscaler/upscale-period: Mon-Sun 06:00-06:01 Europe/Zurich
  hpaAnnotations:
    testing: hpaannotations
  podAnnotations:
    thisisapod: annotation
service:
  enabled: true
  name: complete
  port: 1337
  portName: foo
  targetPort: 9001
  type: ClusterIP
ingress:
  enabled: true
  className: alb
  hosts:
    - www.example.com
    - doc.example.com
scale:
  minReplicas: 2
  maxReplicas: 15
  cpuThresholdPercentage: 80
probe:
  liveness: /api/health
  readiness: /api/health
resources:
  requests:
    cpu: 1
    memory: 1Gi
  limits:
    memory: 2Gi
env:
  FEED_BASE_URL: https://www.feed-url.com

extraEnvFrom:
  - configMapRef:
      name: complete-configmap

extraObjects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: complete-configmap
      namespace: default
    data:
      key1: value1
      key2: value2

nodeSelector:
  provisioner-group: general
  kubernetes.io/arch: amd64

tolerations:
  - key: karpenter.sh/default
    operator: Exists
    effect: NoSchedule

externalSecrets:
  secretNames:
    - "complete/databaseCredentials"

targetGroupBinding:
  enabled: true
  targetGroupARN: arn:aws:elasticloadbalancing:us-west-2:123456789012:targetgroup/complete/1234567890123456
  annotations:
    foo: bar

serviceAccountName: cool service
aws_iam_role_arn: arn:aws:iam::123456789012:role/complete

initContainer:
  enabled: true
  name: initcontainer
  image: busybox
  image_tag: 1.31.1
  command:
    - "sh"
    - "-c"
  args:
    - "echo Hello, DAI!"
