{{- include "generic.validateValues" . -}}
{{- include "generic.validateWorkload" . -}}
{{- if and .Values.workload.enabled (eq (.Values.workload.type | default "deployment") "daemonset") }}
apiVersion: apps/v1
kind: DaemonSet
{{- include "generic.workloadMetadata" . }}
spec:
  {{- with .Values.workload.revisionHistoryLimit }}
  revisionHistoryLimit: {{ . }}
  {{- end }}
  {{- with .Values.workload.minReadySeconds }}
  minReadySeconds: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "generic.selectorLabels" . | nindent 6 }}
  updateStrategy:
    {{- if .Values.workload.updateStrategy }}
    {{- toYaml .Values.workload.updateStrategy | nindent 4 }}
    {{- else }}
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.workload.maxUnavailable | default 1 }}
      {{- with .Values.workload.maxSurge }}
      maxSurge: {{ . }}
      {{- end }}
    {{- end }}
  {{- include "generic.podTemplateSpec" . | nindent 2 }}
{{- end }}
