{{- include "generic.validateValues" . -}}
{{- if .Values.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "generic.fullname" . }}
  namespace: {{ include "generic.namespace" . }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
    {{- with .Values.workloadLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.workloadAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.deployment.replicas | default 1 }}
  {{- end }}
  {{- with .Values.deployment.revisionHistoryLimit }}
  revisionHistoryLimit: {{ . }}
  {{- end }}
  {{- with .Values.deployment.progressDeadlineSeconds }}
  progressDeadlineSeconds: {{ . }}
  {{- end }}
  {{- with .Values.deployment.minReadySeconds }}
  minReadySeconds: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "generic.selectorLabels" . | nindent 6 }}
  {{- with .Values.deployment.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    {{- include "generic.podTemplate" . | nindent 4 }}
{{- end }}
{{- range $name, $deployment := .Values.extraDeployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "generic.fullname" $ }}-{{ $name }}
  namespace: {{ include "generic.namespace" $ }}
  labels:
    {{- include "generic.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
    {{- with $deployment.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not $deployment.hpa }}
  replicas: {{ $deployment.replicas | default 1 }}
  {{- end }}
  {{- with $deployment.revisionHistoryLimit }}
  revisionHistoryLimit: {{ . }}
  {{- end }}
  {{- with $deployment.progressDeadlineSeconds }}
  progressDeadlineSeconds: {{ . }}
  {{- end }}
  {{- with $deployment.minReadySeconds }}
  minReadySeconds: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "generic.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $name }}
  {{- with $deployment.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    {{- include "generic.deploymentPodTemplate" (dict "root" $ "deployment" $deployment "componentName" $name) | nindent 4 }}
{{- end }}
