{{- if and .Values.persistence.enabled (not .Values.persistence.volumeClaimTemplate) }}
{{- if .Values.persistence.volumes }}
{{- range $name, $pvc := .Values.persistence.volumes }}
{{- if $pvc.enabled | default true }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-%s" (include "generic.fullname" $) $name }}
  namespace: {{ include "generic.namespace" $ }}
  labels:
    {{- include "generic.labels" $ | nindent 4 }}
    {{- with $pvc.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $pvc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $pvc.accessModes }}
  accessModes:
    {{- toYaml $pvc.accessModes | nindent 4 }}
  {{- else if $pvc.accessMode }}
  accessModes:
    - {{ $pvc.accessMode }}
  {{- else }}
  accessModes:
    - ReadWriteOnce
  {{- end }}
  {{- with $pvc.volumeMode }}
  volumeMode: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ $pvc.size | default "8Gi" }}
  {{- if $pvc.storageClass }}
  {{- if eq "-" $pvc.storageClass }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ $pvc.storageClass }}
  {{- end }}
  {{- end }}
  {{- with $pvc.selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $pvc.volumeName }}
  volumeName: {{ . }}
  {{- end }}
  {{- with $pvc.dataSource }}
  dataSource:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $pvc.dataSourceRef }}
  dataSourceRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- else }}
{{/* Single PVC for backward compatibility */}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "generic.pvcName" . }}
  namespace: {{ include "generic.namespace" . }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
    {{- with .Values.persistence.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.persistence.accessModes }}
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  {{- else }}
  accessModes:
    - {{ .Values.persistence.accessMode | default "ReadWriteOnce" }}
  {{- end }}
  {{- with .Values.persistence.volumeMode }}
  volumeMode: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "8Gi" }}
  {{- if .Values.persistence.storageClass }}
  {{- if eq "-" .Values.persistence.storageClass }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  {{- end }}
  {{- with .Values.persistence.selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.persistence.volumeName }}
  volumeName: {{ . }}
  {{- end }}
  {{- with .Values.persistence.dataSource }}
  dataSource:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.persistence.dataSourceRef }}
  dataSourceRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
