{{- include "generic.validateValues" . -}}
{{- include "generic.validateWorkload" . -}}
{{- if and .Values.workload.enabled (eq (.Values.workload.type | default "deployment") "statefulset") }}
apiVersion: apps/v1
kind: StatefulSet
{{- include "generic.workloadMetadata" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.workload.replicas | default 1 }}
  {{- end }}
  {{- with .Values.workload.revisionHistoryLimit }}
  revisionHistoryLimit: {{ . }}
  {{- end }}
  {{- with .Values.workload.minReadySeconds }}
  minReadySeconds: {{ . }}
  {{- end }}
  serviceName: {{ .Values.workload.serviceName | default (include "generic.fullname" .) }}
  podManagementPolicy: {{ .Values.workload.podManagementPolicy | default "OrderedReady" }}
  selector:
    matchLabels:
      {{- include "generic.selectorLabels" . | nindent 6 }}
  updateStrategy:
    {{- if .Values.workload.updateStrategy }}
    {{- toYaml .Values.workload.updateStrategy | nindent 4 }}
    {{- else }}
    type: RollingUpdate
    {{- if .Values.workload.partition }}
    rollingUpdate:
      partition: {{ .Values.workload.partition }}
    {{- end }}
    {{- end }}
  {{- if .Values.workload.volumeClaimTemplates }}
  volumeClaimTemplates:
    {{- range $name, $pvc := .Values.workload.volumeClaimTemplates }}
    - metadata:
        name: {{ $name }}
        {{- with $pvc.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      spec:
        {{- with $pvc.accessModes }}
        accessModes:
          {{- toYaml . | nindent 10 }}
        {{- else }}
        accessModes:
          - ReadWriteOnce
        {{- end }}
        {{- with $pvc.storageClassName }}
        storageClassName: {{ . }}
        {{- end }}
        {{- with $pvc.dataSource }}
        dataSource:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with $pvc.dataSourceRef }}
        dataSourceRef:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        resources:
          requests:
            storage: {{ $pvc.size | default "8Gi" }}
        {{- with $pvc.selector }}
        selector:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with $pvc.volumeMode }}
        volumeMode: {{ . }}
        {{- end }}
    {{- end }}
  {{- else if and .Values.persistence.enabled .Values.persistence.volumeClaimTemplate }}
  volumeClaimTemplates:
    - metadata:
        name: data
        {{- with .Values.persistence.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      spec:
        {{- with .Values.persistence.accessModes }}
        accessModes:
          {{- toYaml . | nindent 10 }}
        {{- else }}
        accessModes:
          - ReadWriteOnce
        {{- end }}
        {{- with .Values.persistence.storageClass }}
        storageClassName: {{ . }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | default "8Gi" }}
        {{- with .Values.persistence.selector }}
        selector:
          {{- toYaml . | nindent 10 }}
        {{- end }}
  {{- end }}
  {{- include "generic.podTemplateSpec" . | nindent 2 }}
{{- end }}
