image_repo: public.ecr.aws/eks-distro/kubernetes/pause
image_tag: "3.9"
service:
  name: minimal
scale:
  enabled: false
port: 3000
resources:
  requests:
    cpu: 1
    memory: 1Gi
  limits:
    memory: 2Gi
