{{- if and .Values.rbac.enabled .Values.serviceAccount.enabled .Values.serviceAccount.create }}
{{- if .Values.rbac.rules }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "app.labels" . | nindent 4 }}
  name: {{ include "app.fullname" . }}
  namespace: {{ include "app.namespace" . }}
rules:
  {{- toYaml .Values.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "app.labels" . | nindent 4 }}
  name: {{ include "app.fullname" . }}
  namespace: {{ include "app.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "app.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "app.serviceAccountName" . }}
    namespace: {{ include "app.namespace" . }}
{{- end }}
{{- end }}
