{{- if .Values.ec2NodeClasses }}
{{- $clusterName := .Values.global.eksDiscovery.clusterName }}
{{- $eksDiscoveryEnabled := .Values.global.eksDiscovery.enabled }}
{{- $eksDiscoveryTags := .Values.global.eksDiscovery.tags }}
{{- range $name, $nodeClass := .Values.ec2NodeClasses }}
{{- if $nodeClass.enabled }}
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: {{ $name }}
  labels:
    {{- include "karpenter-resources.labels" $ | nindent 4 }}
spec:
  {{- with $nodeClass.kubelet }}
  kubelet:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- if $nodeClass.amiFamily }}
  amiFamily: {{ $nodeClass.amiFamily }}
  {{- end }}

  {{- if and $eksDiscoveryEnabled $eksDiscoveryTags.subnets }}
  subnetSelectorTerms:
    - tags:
        {{- $hasDiscoveryKey := false }}
        {{- range $key, $value := $eksDiscoveryTags.subnets }}
        {{- if eq $key "karpenter.sh/discovery" }}
        {{- $hasDiscoveryKey = true }}
        {{- if $value }}
        {{ $key }}: {{ $value | quote }}
        {{- else if $clusterName }}
        {{ $key }}: {{ $clusterName | quote }}
        {{- end }}
        {{- else if $value }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
        {{- if not $hasDiscoveryKey }}
        karpenter.sh/discovery: {{ $clusterName | quote }}
        {{- end }}
  {{- else if and $eksDiscoveryEnabled $clusterName (not $eksDiscoveryTags) }}
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ $clusterName | quote }}
  {{- else if not $eksDiscoveryEnabled }}
  {{- with $nodeClass.subnetSelectorTerms }}
  subnetSelectorTerms:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}

  {{- if and $eksDiscoveryEnabled $eksDiscoveryTags.securityGroups }}
  securityGroupSelectorTerms:
    - tags:
        {{- $hasDiscoveryKey := false }}
        {{- range $key, $value := $eksDiscoveryTags.securityGroups }}
        {{- if eq $key "karpenter.sh/discovery" }}
        {{- $hasDiscoveryKey = true }}
        {{- if $value }}
        {{ $key }}: {{ $value | quote }}
        {{- else if $clusterName }}
        {{ $key }}: {{ $clusterName | quote }}
        {{- end }}
        {{- else if $value }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
        {{- if not $hasDiscoveryKey }}
        karpenter.sh/discovery: {{ $clusterName | quote }}
        {{- end }}
  {{- else if and $eksDiscoveryEnabled $clusterName (not $eksDiscoveryTags) }}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ $clusterName | quote }}
  {{- else if not $eksDiscoveryEnabled }}
  {{- with $nodeClass.securityGroupSelectorTerms }}
  securityGroupSelectorTerms:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}

  {{- if $nodeClass.role }}
  role: {{ $nodeClass.role }}
  {{- else if and $.Values.global $.Values.global.role }}
  role: {{ $.Values.global.role }}
  {{- end }}


  {{- with $nodeClass.amiSelectorTerms }}
  amiSelectorTerms:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with $nodeClass.capacityReservationSelectorTerms }}
  capacityReservationSelectorTerms:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with $nodeClass.tags }}
  tags:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with $nodeClass.metadataOptions }}
  metadataOptions:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with $nodeClass.blockDeviceMappings }}
  blockDeviceMappings:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- if hasKey $nodeClass "instanceStorePolicy" }}
  instanceStorePolicy: {{ $nodeClass.instanceStorePolicy }}
  {{- end }}

  {{- if $nodeClass.userData }}
  userData: |
    {{- $nodeClass.userData | nindent 4 }}
  {{- end }}

  {{- with $nodeClass.marketOptions }}
  marketOptions:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- if $nodeClass.detailedMonitoring }}
  detailedMonitoring: {{ $nodeClass.detailedMonitoring }}
  {{- end }}

  {{- if hasKey $nodeClass "associatePublicIPAddress" }}
  associatePublicIPAddress: {{ $nodeClass.associatePublicIPAddress }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
