image_repo: "registry/capella-scraper"
image_tag: "1.0.1"
capellaFQDN: "my.test.cloud.couchbase.com"
jobName: "capella-test"
scrapeUser: "admin"
scrapePass: "password"
serviceAccountName: "default"  # Using default SA for CI tests
