{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "webapp.name" . }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    type: {{ .Chart.Name }}
    app: {{ include "webapp.name" . }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
{{- end}}
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
      {{- .Values.ingress.hosts | toYaml | nindent 8 }}
      secretName: {{ include "webapp.name" . }}-tls
{{- end }}
  rules:
  {{- if not (empty .Values.ingress.hosts) }}
  {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
        {{- range $.Values.ingress.paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.service.name | default (include "webapp.name" $ ) }}
                port:
                  number: {{ $.Values.service.port }}
        {{- end }}
  {{- end }}
{{- else }}
    - http:
        paths:
        {{- range $.Values.ingress.paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.service.name | default (include "webapp.name" $ ) }}
                port:
                  number: {{ $.Values.service.port }}
        {{- end }}
  {{- end }}
{{- end }}
