{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ default (include "webapp.name" .) .Values.service.name }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    type: {{ .Chart.Name }}
    app: {{ include "webapp.name" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort:  {{ default .Values.service.targetPort .Values.port }}
  selector:
    type: {{ .Chart.Name }}
    app: {{ include "webapp.name" . }}
{{- end }}
